<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        Event::query()->delete();

        Event::insert([
            [
                'user_id' => 1,
                'title' => 'Echipa 1 vs echipa 2',
                'slug' => 'meci-fotball',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'location' => 'Arena Nationala',
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11394.499745760033!2d26.15960368433235!3d44.44085527729191!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1f932b120b96b%3A0x53a7021f11d624a4!2sNational%20Arena!5e0!3m2!1sen!2sro!4v1780813780855!5m2!1sen!2sro',
                'ticket_url' => 'https://loremipsum.io/generator/',
                'ticket_label' => 'CuMpaRa Bilete',
                'start_date' => '2026-06-08 12:00:00',
                'end_date' => '2026-06-09 12:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Trapper related event',
                'slug' => 'trapper-event',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae venenatis urna, non interdum augue. Aliquam sit amet urna rhoncus, venenatis mauris sed, interdum ex. Nunc ullamcorper vulputate nisl et sodales. Sed id elementum mauris. In lobortis leo ante, eu blandit purus varius in. Mauris sit amet lacus non lectus congue suscipit ac id ligula. Cras rutrum sit amet nisi sit amet pharetra. Nunc mollis hendrerit mauris. Duis ut enim ac nulla ullamcorper interdum sed nec nisl. Vestibulum vel varius libero, quis ultricies nulla.',
                'location' => 'Tot Arena nationala',
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11394.499745760033!2d26.15960368433235!3d44.44085527729191!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1f932b120b96b%3A0x53a7021f11d624a4!2sNational%20Arena!5e0!3m2!1sen!2sro!4v1780813780855!5m2!1sen!2sro',
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Evan_MacMillan',
                'ticket_label' => 'See Trapper Live',
                'start_date' => '2026-06-09 04:00:00',
                'end_date' => '2026-06-09 05:00:00',
                'image' => null,
                'is_published' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Come see the Wraith Live',
                'slug' => 'wraith-event',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae venenatis urna, non interdum augue. Aliquam sit amet urna rhoncus, venenatis mauris sed, interdum ex. Nunc ullamcorper vulputate nisl et sodales. Sed id elementum mauris. In lobortis leo ante, eu blandit purus varius in. Mauris sit amet lacus non lectus congue suscipit ac id ligula. Cras rutrum sit amet nisi sit amet pharetra. Nunc mollis hendrerit mauris. Duis ut enim ac nulla ullamcorper interdum sed nec nisl. Vestibulum vel varius libero, quis ultricies nulla.',
                'location' => 'Arena Nationala',
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11394.499745760033!2d26.15960368433235!3d44.44085527729191!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1f932b120b96b%3A0x53a7021f11d624a4!2sNational%20Arena!5e0!3m2!1sen!2sro!4v1780813780855!5m2!1sen!2sro',
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Philip_Ojomo',
                'ticket_label' => 'See Wraith Live',
                'start_date' => '2026-06-10 12:00:00',
                'end_date' => '2026-06-11 01:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Hillbilly coming near you',
                'slug' => 'hillbilly-event',
                'description' => 'Praesent aliquam, tellus ut consectetur malesuada, turpis nibh lacinia dolor, et luctus turpis purus ac lectus. Integer ut velit eget mauris pretium elementum nec sit amet arcu. Donec consequat elit ex, quis dictum purus molestie non. Integer mollis, elit ac suscipit tincidunt, ex diam euismod lacus, at interdum diam nibh sed tortor. In eget dolor ex. Praesent faucibus porttitor laoreet. Integer eu nisl eleifend, congue purus ut, faucibus tellus. Phasellus neque enim, tempor at interdum quis, pretium id ex.',
                'location' => 'Ceva Muzeu',
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11396.047761318498!2d26.12748204089709!3d44.432917290062534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1ff23b1ea7837%3A0x805edd6e8ded5a7a!2sMuseum%20of%20Romanian%20Records!5e0!3m2!1sen!2sro!4v1780814584807!5m2!1sen!2sro',
                'ticket_url' => null,
                'ticket_label' => null,
                'start_date' => '2026-06-13 00:00:00',
                'end_date' => '2026-06-13 02:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'See the Nurse near you',
                'slug' => 'nurse-event',
                'description' => 'A new varmint has entered the arena. I spotted her as she, somehow, moved through a wall. Clad in bandages that tell an untold tale of something horrid. This...nurse as it seems, brings me new angst during my lonely nights, as my mind runs amok.',
                'location' => 'Crotus Prenn Asylum',
                'maps_url' => null,
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Sally_Smithson',
                'ticket_label' => 'See the Nurse',
                'start_date' => '2026-06-01 09:00:00',
                'end_date' => '2026-06-01 11:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'The one and only Michael Myers',
                'slug' => 'michael-myers',
                'description' => 'Something, or rather someone, is here now. I\'ve never seen this... Shape before. A man hiding behind a mask. He comes with a determination. But more worrying, he comes with an apparent grasp of the hunt. He does not strike me as someone who even went unwillingly to this place. Is there more to this being than I can fathom?',
                'location' => 'Haddonfield',
                'maps_url' => null,
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Michael_Myers',
                'ticket_label' => 'Hug Michael Today',
                'start_date' => '2026-06-02 12:00:00',
                'end_date' => '2026-06-02 23:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Lisa Sherwood — The Hag',
                'slug' => 'lisa-sherwood-the-hag',
                'description' => 'A new terror stalks the darkness; her appearance strikes me as more intense than the others after but a glimpse of her haggard silhouette. Twisted and torn in unspeakable ways, with greyish dead skin stretched out over her emaciated body. Her arm is a horrid overgrown deformity capable of slashing through both flesh and bone alike. Her very presence speaks of endless torture similar to mine. I wonder - did she refuse the entity\'s calling until broken or did she wish for this?',
                'location' => 'Backwater Swamp',
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11396.047761318498!2d26.12748204089709!3d44.432917290062534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1ff23b1ea7837%3A0x805edd6e8ded5a7a!2sMuseum%20of%20Romanian%20Records!5e0!3m2!1sen!2sro!4v1780814584807!5m2!1sen!2sro',
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Lisa_Sherwood',
                'ticket_label' => 'Buy tickets here',
                'start_date' => '2026-06-03 11:00:00',
                'end_date' => '2026-06-03 12:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Herman Carter',
                'slug' => 'the-doctor',
                'description' => 'I have difficulty keeping my sanity. Each day, this altering world provides me with new trials. A man wearing the robes of a doctor crossed my path. From afar, I witness him walking around, searching.. But he was not...normal. Eyes and mouth pried open, in a painful and disturbing way. Where do these fiends stem from? I do not trust him, he looks like he wants to bring pain, not healing? I will stay away, it is the wisest thing to do.',
                'location' => "Léry's Memorial Institute",
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11396.047761318498!2d26.12748204089709!3d44.432917290062534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1ff23b1ea7837%3A0x805edd6e8ded5a7a!2sMuseum%20of%20Romanian%20Records!5e0!3m2!1sen!2sro!4v1780814584807!5m2!1sen!2sro',
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Herman_Carter',
                'ticket_label' => 'Get a consult now',
                'start_date' => '2026-06-16 00:00:00',
                'end_date' => '2026-06-17 00:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Anna',
                'slug' => 'the-huntress',
                'description' => 'A figure clad in the head of a hare. A most disturbing sight. This new foe holds something human within her. Some shards of ordinary life. She seems to be a hunter. I have met many different beings in this place, but this is the first one with a natural skill of hunting. In any other place one could deem it a talent. But her knack for tracking, capturing and killing is something else here. There is something else in her too, she seems to seek something.',
                'location' => 'Red Forset',
                'maps_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11396.047761318498!2d26.12748204089709!3d44.432917290062534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1ff23b1ea7837%3A0x805edd6e8ded5a7a!2sMuseum%20of%20Romanian%20Records!5e0!3m2!1sen!2sro!4v1780814584807!5m2!1sen!2sro',
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Anna',
                'ticket_label' => 'Share a kiss with her',
                'start_date' => '2026-06-19 00:00:00',
                'end_date' => '2026-06-19 01:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Bubba Sawyer',
                'slug' => 'the-cannibal',
                'description' => '"Whether Killers perform their heinous acts by the compulsions of their diseased minds, or if they are forced into them by external pressures, has long been a matter of debate. But for one Killer, nature and nurture are inextricably linked. Leatherface kills not from a desire to exert his will over others, to satisfy carnal urges, or even to quiet the voices in his head. He kills because he is scared. Scared that others will hurt him; scared that his family will be displeased with him, scared that their shared willingness to eat human flesh will be discovered."',
                'location' => 'Somewhere close',
                'maps_url' => null,
                'ticket_url' => 'https://deadbydaylight.fandom.com/wiki/Bubba_Sawyer',
                'ticket_label' => 'Dine with him',
                'start_date' => '2026-06-25 11:00:00',
                'end_date' => '2026-06-25 12:00:00',
                'image' => null,
                'is_published' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
